#!/bin/bash
set -euo pipefail

# Overwrite the package.json-backed version module with a compile-time constant
# so standalone binaries do not need package.json next to the executable.
# Restore the source file afterward so the working tree stays clean.
VERSION=$(node -p "require('./package.json').version")
VERSION_SOURCE="src/version.ts"
VERSION_BACKUP="$(mktemp)"
cp "$VERSION_SOURCE" "$VERSION_BACKUP"

restore_version() {
  cp "$VERSION_BACKUP" "$VERSION_SOURCE"
  rm -f "$VERSION_BACKUP"
}
trap restore_version EXIT

cat >"$VERSION_SOURCE" <<EOF
// Generated by scripts/build.sh — do not edit; regenerated on every build.
export const VERSION = "$VERSION";
EOF

bun build src/index.ts --compile --outfile dist/ai
bun build src/summary/index.ts --compile --outfile dist/ai-summary
bun build src/meeting/index.ts --compile --outfile dist/ai-meeting
